version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "8000:8000"
    #volumes:
    #  - ./data:/app/data # No need to persist user files, end session will delete all files and keys
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    # No API key required here; provided dynamically at runtime.

  frontend:
    image: python:3.12.6-slim
    container_name: frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: >
      bash -c "
        pip install streamlit &&
        streamlit run frontend.py --server.port=8501
        "